apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprinkler-detector
  labels:
    app: sprinkler-detector
spec:
  selector:
    matchLabels:
      app: sprinkler-detector
  replicas: 1
  template:
    metadata:
      labels:
        app: sprinkler-detector
    spec:
      containers:
      - name: sprinkler-detector
        image: localhost:32000/sprinkler-detector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: STREAM_URI
          valueFrom:
            secretKeyRef:
              name: sprinkler-detector
              key: stream_uri
        - name: DISPLAY_FPS
          value: "1"
        - name: CONFIDENCE_THRESHOLD
          value: "0.6"
